Fix data corruption during compression of large chunks (#11525)
There are 3 problems involved:
1. `ArrowMsg::uncompressed_size` is defined as an `int32`. That issue
speaks for itself.
2. The encoding path tracks payload sizes using `usize`, and then
silently cast them to `int32` when encoding the Protobuf data, leading
to gibberish and crashes during decoding.
3. `lz4_flex` has similar casting bugs: it can encode 64bit values but
cannot decode them. Once again the `as` keyword is involved.

This PR fixes 1 and 2. All the changes are backward and forward
compatible because:
* In protobuf, `uint64` is a strict superset of `int32`: both are
unsigned varints on the wire.
* There exist no valid RRD files out there with negative values for
`uncompressed_size`.

We can already log much bigger chunks than before, but not too big,
otherwise `lz4` itself will during decoding:
```
thread 'decompress' panicked at 'attempt to add with overflow'
lz4_flex-0.11.5/src/block/decompress_safe.rs:39
stack backtrace:
   6: core::panicking::panic_fmt
             at core/src/panicking.rs:75:14
   7: core::panicking::panic_const::panic_const_add_overflow
             at core/src/panicking.rs:175:17
   8: std::sys::backtrace::__rust_begin_short_backtrace
   9: core::ops::function::FnOnce::call_once{{vtable.shim}}
  10: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1966:9
      <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:1966:9
      std::sys::pal::unix::thread::Thread::new::thread_start
             at std/src/sys/pal/unix/thread.rs:97:17
  11: <unknown>
  12: <unknown>
```

I'll have a follow-up PR for the `lz4_flex` issue.

---

* Half of fixing https://github.com/rerun-io/rerun/issues/11516
  * The other half requires patching `lz4_flex` (on it)

---

Checks:
* [x] `rerun` with `--nb_scans 2000`
* [x] `rerun rrd stats` with `--nb_scans 2000`
* [x] :no_entry: `rerun` with `--nb_scans 3000` -> bug in lz4
* [x] :no_entry: `rerun rrd stats` with `--nb_scans 3000` -> bug in lz4
* [x] All dataplatform test suites pass
* [x] Can load old RRDs no problem