Forbid footer-less registration on Rerun Cloud
Title.

Verify:
```
$ ls ../dataplatform/data/xxx/*
../dataplatform/data/xxx/Fri_Apr_21_17:52:22_2023.rrd
../dataplatform/data/xxx/Fri_May_12_16:30:58_2023.rrd

$ pixi run rerun rrd verify ../dataplatform/data/xxx/*
"../dataplatform/data/xxx/Fri_May_12_16:30:58_2023.rrd": Missing RRD manifest
Error: Verification failed with 1 errors
```

Register:
```
$ REDAP_URI=rerun+http://localhost:51234 pixi run uvpy scripts/register_recordings.py --name xxx ./data/xxx/ --passes 1 --force-replace

registering all the following recordings to rerun+http://localhost:51234:
* /home/cmc/dev/rerun-io/reality/dataplatform/data/xxx

pass 1 out of 1…Traceback (most recent call last):
  File "/home/cmc/dev/rerun-io/reality/dataplatform/scripts/register_recordings.py", line 180, in <module>
    register_directories(args.wait_time)
  File "/home/cmc/dev/rerun-io/reality/dataplatform/scripts/register_recordings.py", line 122, in register_directories
    tasks.wait(wait)
  File "/home/cmc/dev/rerun-io/reality/rerun/rerun_py/rerun_sdk/rerun/catalog/_registration_handle.py", line 106, in wait
    segment_ids = self._internal.wait(timeout_secs)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Registration failed for the following URIs:
file:///home/cmc/dev/rerun-io/reality/dataplatform/data/xxx/Fri_Apr_21_17:52:22_2023.rrd: error while processing segments: InvalidArguments: failed computing RRD manifest: attempting to register data for segment ILIAD_7ae1bcff_2023_05_12_16h_30m_58s that is lacking RRD footers: file:///home/cmc/dev/rerun-io/reality/dataplatform/data/xxx/Fri_May_12_16:30:58_2023.rrd (crates/redap_manifest_registry/src/dataset/api.rs:2216:26)
file:///home/cmc/dev/rerun-io/reality/dataplatform/data/xxx/Fri_May_12_16:30:58_2023.rrd: error while processing segments: InvalidArguments: failed computing RRD manifest: attempting to register data for segment ILIAD_7ae1bcff_2023_05_12_16h_30m_58s that is lacking RRD footers: file:///home/cmc/dev/rerun-io/reality/dataplatform/data/xxx/Fri_May_12_16:30:58_2023.rrd (crates/redap_manifest_registry/src/dataset/api.rs:2216:26)
```

Patch:
```
$ pixi run rerun rrd migrate ../dataplatform/data/xxx/*
Migrating 2 .rrd file(s)…
✅ 2 file(s) successfully migrated.

$ rm -f ../dataplatform/data/xxx/*.backup.rrd
removed '../dataplatform/data/xxx/Fri_Apr_21_17:52:22_2023.backup.rrd'
removed '../dataplatform/data/xxx/Fri_May_12_16:30:58_2023.backup.rrd'
```

Re-verify:
```
$ pixi run rerun rrd verify ../dataplatform/data/xxx/*
2 files verified without error.
```

Re-register:
```
$ REDAP_URI=rerun+http://localhost:51234 pixi run uvpy scripts/register_recordings.py --name xxx ./data/xxx/ --passes 1 --force-replace

registering all the following recordings to rerun+http://localhost:51234:
* /home/cmc/dev/rerun-io/reality/dataplatform/data/xxx

pass 1 out of 1… done in 0.23 seconds

registration successful in 0.23 seconds
  Registered chunks: 919
  Registered size:   90.4 MB
```

---

TODO:
* [x] Rebase once the S3 config thing finally made it through the merge
queue

Source-Ref: 872eb978d1e7fcb12bd72b09b804c10520b58cd1