fix: broken WorkOS: add back support for RS256 signatures
* https://rerunio.slack.com/archives/C07T0LFT5BQ/p1772756725206719
We accidentally dropped in #1024.

This PR:
* adds it back by implementing the corresponding provider (thanks Claude
for the help).
* send more information back to the client; change the SDK so that it
actually returns this information to the human behind it.
* Log the full error server side, but not too often.
* Avoid a couple of footguns I stumbled upon that were preventing me to
debug locally.

The SDK would now scream:

```
PermissionError: invalid credentials: unsupported signature algorithm
```

Before it was
```
PermissionError: verifying server credentials
```

---------

Signed-off-by: Andrea Reale <andrea@rerun.io>

Source-Ref: 230acaa174b73fc0e47f1def47d49a0e612bd659
(cherry picked from commit a81349d9eee5adee9530bb3e541ab3db2a39cdce)