custom NotFound/AlreadyExists python errors (#11529)
### Related
Follow-up to #11513


### What
Use custom python error types instead of of built-in
`FileNotFoundError`/`FileExistsError`.

### Manual testing
```
In [1]: import rerun
DEV ENVIRONMENT DETECTED! Re-importing rerun from: /var/home/andrea/workspace/rerun.io/rerun/rerun_py/rerun_sdk

In [2]: exception = rerun.catalog.AlreadyExistsError("entry exists")

In [3]: raise exception
---------------------------------------------------------------------------
AlreadyExistsError                          Traceback (most recent call last)
Cell In[3], line 1
----> 1 raise exception

AlreadyExistsError: entry exists
```

---------

Signed-off-by: Andrea Reale <andrea@rerun.io>