Upgrade Zombies Script: Don't Query All Issues/ Check External Issues (#10813)
### Related
Closes #10801 and closes #10798 by making it unnecessary with zombie
support

### What
This is basically just a full refactor of the zombie script. I asked
Claude to add external repo support then I deduped code, removed the
need to scan all issues on all repos, progress bar etc. This could
probably still be cleaned up a little more if someone felt strongly but
we had globals littered around before.

1. Go through all files
2. Try to match every line to internal or external issue format
3. Check if that issue is closed by directly querying github for it
(cache results)
4. Print everything out at the end

The one annoying thing I couldn't resolve because I think it is a github
limitation is being able to check private repos under the rerun org with
a fine grained token. A classic token with repo scope allows you to
check all private repos you have access to but a fine grained doesn't
unless generated under the organization itself which requires an admin
to approve. Note that this should work without a token at all but with a
lower rate limit/no private repo access.

Before
```
...snip...
done fetching issues
./crates/viewer/re_renderer/src/device_caps.rs:478: wgpu::Backends::GL // TODO(#8559): Fix WebGPU on Safari
Traceback (most recent call last):
  File "/Users/nick/repos/rerun/scripts/zombie_todos.py", line 258, in <module>
    main()
  File "/Users/nick/repos/rerun/scripts/zombie_todos.py", line 254, in main
    raise ValueError("Clean your zombies!")
ValueError: Clean your zombies!

real    1m43.139s
user    0m9.786s
sys     0m6.694s
```

After
```
time pixi run python scripts/zombie_todos.py  --token <token>
Processing 8499 files...
Using 16 worker threads...
Processing files: 100%|███████████████████████████████████████████████████████████████████████████████████████████████| 8499/8499 [00:21<00:00, 397.97file/s]
./crates/viewer/re_ui/src/alert.rs:65: .outer_margin(1.0) // Needed because we set clip_rect_margin. TODO(emilk/egui#4019): remove clip_rect_margin
./crates/viewer/re_renderer/src/device_caps.rs:478: wgpu::Backends::GL // TODO(#8559): Fix WebGPU on Safari
./crates/viewer/re_renderer/src/view_builder.rs:617: // TODO(gfx-rs/wgpu#1453): Note that this is a limitation that will be lifted in future versions of wgpu.
./crates/store/re_types/src/testing/datatypes/affix_fuzzer21_ext.rs:3: // TODO(apache/arrow-rs#7411)
./rerun_py/src/dataframe/recording.rs:36: // TODO(rerun-io/dataplatform#405): interface with remote data needs to be reimplemented
./examples/python/open_photogrammetry_format/open_photogrammetry_format.py:94: # TODO(Pix4D/pyopf#6): https://github.com/Pix4D/pyopf/issues/6


Cache statistics:
  Total unique issues checked: 208
  Closed issues found: 6
  Open/unknown issues: 202
  Cache hits: 321, Cache misses: 266
Traceback (most recent call last):
  File "/Users/nick/repos/rerun/scripts/zombie_todos.py", line 338, in <module>
    main()
  File "/Users/nick/repos/rerun/scripts/zombie_todos.py", line 334, in main
    raise ValueError("Clean your zombies!")
ValueError: Clean your zombies!

real    0m29.186s
user    0m5.713s
sys     0m4.067s
```