Revert "Show list of enabled feature with `rerun --version`" (#7770)
* Reverts rerun-io/rerun#7744

The PR caused the crate publishing step to fail with this message:

```
Failed to publish re_sdk:
error: failed to verify package tarball

Caused by:
  Source directory was modified by build.rs during cargo publish. Build scripts should not modify anything outside of OUT_DIR.
  Added: /home/runner/work/rerun/rerun/target/package/re_sdk-0.19.0-alpha.9/Cargo.lock
```


(https://github.com/rerun-io/rerun/actions/runs/11350925172/job/31573371223)

I don't know why, and this close to release I don't have time to figure
out why.