Fix error messages for potentially recoverable MCAP files
### What

When opening an MCAP file without valid summary, only a cryptic
low-level error message was provided.

* Wrap low-level summary errors in a dedicated error variant that
suggests the user to enable `recover`
* Fix the non-descriptive "Bad magic number" error to better explain
what is actually wrong

**Example previously:**
```
Error: Failed to inspect MCAP file
File path: /Users/michael/datasets/autoware_all_sensors_broken.mcap: Bad magic number
```

**Now**
```
Error: MCAP summary is missing or corrupt; try reopening it with recovery enabled. Details: MCAP file does not end with the expected magic bytes
```

I removed the "File path: .." from the CLI error message. The file path
is part of the CLI command, so no need to repeat it 🤷

Python `McapReader` wraps the same error message in a `ValueError`.

### Testing

* see updated Rust/Python unit tests
* manual test with CLI

### Compatibility

Just fixing bad error messages.

Source-Ref: fc6319380a7288298a1bb2fc6d28e26041c2a716