`rerun rrd verify` now checks for the presence of RRD manifests
Title.

```sh
# Going as expected
$ rerun rrd verify ../dataplatform/data/trossen_technical_50/*/*.rrd
200 files verified without error.

# A genuine bad surprise I just had 😱
$ rerun rrd verify ../dataplatform/data/droidnano/*
"../dataplatform/data/droidnano/Fri_May_12_16:30:58_2023.rrd": Missing RRD manifest
Error: Verification failed with 1 errors
```

Source-Ref: 23f2bbf24ab8fb978af8b2c87cce0fb6cc60f4b8