Don't bench the re_query binaries (#6160)
### What
This was causing nightly to fail with:
```
error: Unrecognized option: 'output-format'
error: bench failed, to rerun pass `-p re_query --bin clamped_zip`
```