Improve task-based registration error display
### Context

We recently introduced a test on property size (to avoid huge
manifests), which makes the task-time registration error potentially
more common. Such error must be sufficiently clear to allow the user to
take corrective action (e.g. do not attempt to register this URI, etc.).

Currently, at the redap level, such task-time registration error is
reported on a per-task-basis. Note that task typically have a batch size
of up to 1000 rrd. On the client side, this was so far very poorly
handled: the task error was repeated for every single rrd covered by
said task. This means that for 1 failed rrd in a task, the error message
would be duplicated up to 1000x.

For example, in a batch registration of 3 rrds (in a single task) with
two failed ones, the following error would be printed:

```
ValueError: Registration failed for the following URIs:
file:///Users/hhip/src/reality/my_scripts/property_error/recording3.rrd: error while processing segments: InvalidArguments: oversized_props2 (file:///Users/hhip/src/reality/my_scripts/property_error/recording2.rrd) registration failed: segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop2:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3205:56), InvalidArguments: oversized_props1 (file:///Users/hhip/src/reality/my_scripts/property_error/recording1.rrd) registration failed: segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop1:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3205:56)
file:///Users/hhip/src/reality/my_scripts/property_error/recording1.rrd: error while processing segments: InvalidArguments: oversized_props2 (file:///Users/hhip/src/reality/my_scripts/property_error/recording2.rrd) registration failed: segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop2:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3205:56), InvalidArguments: oversized_props1 (file:///Users/hhip/src/reality/my_scripts/property_error/recording1.rrd) registration failed: segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop1:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3205:56)
file:///Users/hhip/src/reality/my_scripts/property_error/recording2.rrd: error while processing segments: InvalidArguments: oversized_props2 (file:///Users/hhip/src/reality/my_scripts/property_error/recording2.rrd) registration failed: segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop2:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3205:56), InvalidArguments: oversized_props1 (file:///Users/hhip/src/reality/my_scripts/property_error/recording1.rrd) registration failed: segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop1:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3205:56)
```

Properly addressing that requires replacing the generic task stuff at
the redap level by a bespoke, typed, per-rrd error/status reporting.
That's future work.

### What

This PR is a low-effort fix to the current error formatting, such that
the error above now becomes:

```
ValueError: Registration failed while processing the following segments:
    InvalidArguments: Segment 'oversized_props2' (file:///Users/hhip/src/reality/my_scripts/property_error/recording2.rrd):
        segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop2:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3203:56)
    InvalidArguments: Segment 'oversized_props1' (file:///Users/hhip/src/reality/my_scripts/property_error/recording1.rrd):
        segment properties (806 KiB) exceed the maximum allowed size (1000 B). Largest properties: property:large_prop1:embedding (806 KiB) (crates/redap_manifest_registry/src/dataset/api.rs:3203:56)

```

Source-Ref: 7917c834d795f7ed1100ba7c37787cee4efe33f1