`re_uri` expects `Timeline` to be serializable (#9358)
`re_uri` expects `Timeline` to be serializable.

### How to repro 

```
cargo build -p re_uri

error[E0277]: the trait bound `Timeline: Serialize` is not satisfied
    --> crates/utils/re_uri/src/lib.rs:46:45
     |
46   | #[derive(Debug, Clone, PartialEq, Eq, Hash, serde::Serialize, serde::Deserialize)]
     |                                             ^^^^^^^^^^^^^^^^ the trait `Serialize` is not implemented for `Timeline`
47   | pub struct TimeRange {
48   |     pub timeline: re_log_types::Timeline,
     |     --- required by a bound introduced by this call

```

Signed-off-by: Andrea Reale <andrea@rerun.io>