Fix CI: Don't pin Pillow version
Seems like when Pillow 10.0.0, Pillow 9.5.0 was yanked causing
CI failures:

```
ERROR: Could not find a version that satisfies the requirement pillow<10,>=9.5.0 (from rerun-sdk) (from versions: none)
ERROR: No matching distribution found for pillow<10,>=9.5.0
```

Let's just not pin the version.
The Python eco-system doesn't seem ready for such things.