[auth] Handle failures to fresh credentials as being unauthenticated (#11868)
### What

Trying to create connection client in python with an expired refresh
token was causing authentication failures, even if connecting to a
server that doesn't require auth.

```
RuntimeError: Internal: verifying credentials: status: 'Unknown error', self: "failed to refresh credentials: {\"error\":\"invalid_grant\",\"error_description\":\"Session has already ended.\"}"
```

This properly handles `SessionExpired` / `Custom` cases and maps them to
`CredentialsProviderError`.