Fix serialization error when fixed-size-native-lists are enclosed in an nullable type (#4515)
### What

The new blueprint refactor ran into an issue when wanting to specify a
nullable uuid (stored as a fixed-size list).

When the outer type was null this would cause a crash:
```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: OutOfSpec("validity mask length must match the number of values")'
```

This PR:
 - Introduces a new fuzzer test that reproduces the problem.
 - Fixes the serializer by special-casing the FixedSizeList path

Best reviewed commit-by-commit.

### Checklist
* [x] I have read and agree to [Contributor
Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and
the [Code of
Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
  * Full build: [app.rerun.io](https://app.rerun.io/pr/4515/index.html)
* Partial build:
[app.rerun.io](https://app.rerun.io/pr/4515/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
- Useful for quick testing when changes do not affect examples in any
way
* [x] The PR title and labels are set such as to maximize their
usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4515)
- [Docs
preview](https://rerun.io/preview/83a99f7d9b89880127d7a96612949fc93574d28c/docs)
<!--DOCS-PREVIEW-->
- [Examples
preview](https://rerun.io/preview/83a99f7d9b89880127d7a96612949fc93574d28c/examples)
<!--EXAMPLES-PREVIEW-->
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)