C++ flexible ComponentBatch, AsComponents, logging unification (#3791)
### What

* Fixes #3050 

This PR introduces two new concepts to our logging/serialization
pipeline that make it much more extensible and make us able to avoid
allocations for (simple) user types.
On top, it simplifies our logging pipelines and - despite template
juggling - should lead to **better** error messages!

The whole thing works with two new trait classes:

* `ComponentBatch<TComponent>`
* this is used wherever we previously used `std::vector<TComponent>` in
archetypes
* can be constructed for every `TInput` for which
`ComponentBatchAdapater<TComponent, TInput>` exists
* the generic implementations of this trait take over
std::vector/array/etc. support which actually opens more ways of feeding
an archetype
* in order to keep it simple (it's free of SFINAE!) there's some slight
usability compromises, check adjustments to examples and tests to learn
more. In particular some type conversions from _constructor arguments_
of `TComponent` no longer work (you have to construct your component
before passing now).
* it's super easy for users to create their own non-generic adapters,
check the unit test!
* data is either owned (via an std::vector) or borrowed. Borrowed means
it holds a pointer which is comes with a safety tradeoff. Behavior can
be controlled explicitly (`borrow(ptr, len)` /
`take_ownership(std::vector&&)`) but adapters typically decide
* `AsComponents<T>`
    * similar to the trait with the same name in Rust!
* everything that is implemented for it can be logged -> There's only
`log` and `try_log` now 🎉
* default implemented for `ComponentBatch`, vector/array/c-array of
components and generated for all archetypes (-> serialization is no
longer part of the archetype struct, but pushed to the trait impl)

Unlike typically with traits, the default of both traits IS implemented,
containing a static_assert (thanks @ankeanke for the idea!!) which gives
a (somewhat readable) error message when there's not batch adapter or
component:

AsComponents failure:
```cpp
struct Foo {};
stream.log("test", Foo{});
```
leads to:
```
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/src/rerun/as_components.hpp:18:9: error: static_assert failed due to requirement 'NoAsComponentsFor<Foo>::value' "AsComponents is not implemented for this type. It is implemented for all built-in archetypes as well as std::vector, std::array, and c-arrays of components. You can add your own implementation by specializing AsComponents<T> for your type T."
        static_assert(
        ^
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/src/rerun/recording_stream.hpp:160:25: note: in instantiation of template class 'rerun::AsComponents<Foo>' requested here
                        AsComponents<Ts>().serialize(archetypes_or_component_batches);
                        ^
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/src/rerun/recording_stream.hpp:137:13: note: in instantiation of function template specialization 'rerun::RecordingStream::try_log<Foo>' requested here
            try_log(entity_path, archetypes_or_component_batches...).log_on_failure();
            ^
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/tests/recording_stream.cpp:527:16: note: in instantiation of function template specialization 'rerun::RecordingStream::log<Foo>' requested here
        stream.log("test", Foo{});
               ^
```

ComponentBatchAdapter failure:
```cpp
struct Foo {
} foo;
rerun::archetypes::Points2D test(foo);
```
```
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/src/rerun/archetypes/../component_batch.hpp:32:9: error: static_assert failed due to requirement 'NoAdapterFor<rerun::components::Position2D, Foo>::value' "ComponentBatchAdapter is not implemented for this type. It is implemented for for single components as well as std::vector, std::array, and c-arrays of components. You can add your own implementation by specializing ComponentBatchAdapter<TComponent, T> for a given component and your input type T."
        static_assert(
        ^
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/src/rerun/archetypes/../component_batch.hpp:95:52: note: in instantiation of template class 'rerun::ComponentBatchAdapter<rerun::components::Position2D, Foo>' requested here
        ComponentBatch(T&& input) : ComponentBatch(TAdapter<T>()(std::forward<T>(input))) {}
                                                   ^
/Users/andreas/dev/rerun-io/rerun/rerun_cpp/tests/recording_stream.cpp:528:42: note: in instantiation of function template specialization 'rerun::ComponentBatch<rerun::components::Position2D>::ComponentBatch<Foo &>' requested here
        rerun::archetypes::Points2D test(foo);
                                         ^
```

Future work:
* `MonoComponentBatch` for mono components - right now mono components
(like transform, but also like MeshProperties which has all triangle
indices 😞) are not adaptable and always full-copy
* ComponentBatch optimization for owned single components
* ComponentBatch stride adapter
* iterate on `to_data_cell` arrow serialization methods to make them fit
better into the system. Since `ComponentBatch` should have strides etc.
in the future, they will need to consume `ComponentBatches` which in
turn need the ability to iterate.
* example demonstrating the new extensibility

### Checklist
* [x] I have read and agree to [Contributor
Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and
the [Code of
Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/3791) (if
applicable)
* [x] The PR title and labels are set such as to maximize their
usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/3791)
- [Docs
preview](https://rerun.io/preview/ec9832449c3416410b9ca4df77cedc379ae85dbd/docs)
<!--DOCS-PREVIEW-->
- [Examples
preview](https://rerun.io/preview/ec9832449c3416410b9ca4df77cedc379ae85dbd/examples)
<!--EXAMPLES-PREVIEW-->
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)