Fix debug assert for missing list item scope
Fixes
```
thread 'main' panicked at 'DEBUG ASSERT: ListItem was not wrapped in list_item_scope()'
re_ui/src/list_item/scope.rs:234
stack backtrace:
   9: core::panicking::panic_fmt
             at core/src/panicking.rs:80:14
  10: re_ui::list_item::scope::LayoutInfoStack::top::{{closure}}
             at re_ui/src/list_item/scope.rs:234:13
      egui::context::Context::data_mut::{{closure}}
             at egui/src/context.rs:1015:31
      egui::context::Context::write
             at egui/src/context.rs:756:9
  11: egui::context::Context::data_mut
             at egui/src/context.rs:1015:14
      re_ui::list_item::scope::LayoutInfoStack::top
             at re_ui/src/list_item/scope.rs:225:13
      re_ui::list_item::list_item::ListItem::ui
             at re_ui/src/list_item/list_item.rs:512:27
  12: re_ui::list_item::list_item::ListItem::show_flat::{{closure}}
             at re_ui/src/list_item/list_item.rs:315:28
      core::ops::function::FnOnce::call_once{{vtable.shim}}
             at core/src/ops/function.rs:250:5
  13: <alloc::boxed::Box<F,A> as core::ops::function::FnOnce<Args>>::call_once
             at alloc/src/boxed.rs:2005:9
  14: egui::ui::Ui::scope_dyn
             at egui/src/ui.rs:2423:19
  15: egui::ui::Ui::scope
             at egui/src/ui.rs:2402:14
  16: re_ui::list_item::list_item::ListItem::show_flat
             at re_ui/src/list_item/list_item.rs:315:12
  17: re_ui::ui_ext::UiExt::list_item_label
             at re_ui/src/ui_ext.rs:683:14
      re_data_ui::instance_path_ui::instance_path_ui
             at re_data_ui/src/instance_path_ui.rs:163:24
  18: re_data_ui::instance_path_ui::<impl re_data_ui::DataUi for re_entity_db::instance_path::InstancePath>::data_ui
             at re_data_ui/src/instance_path_ui.rs:74:9
  19: re_data_ui::item_ui::instance_hover_card_ui
             at re_data_ui/src/item_ui.rs:524:19
```

Source-Ref: 02a9f4cf6a4727f04833304dd382143ba4cd6635