Pin ci machines with Vulkan setup to Ubuntu 22.04 (#8721)
`ubuntu-latest` got updated to imply Ubuntu 24. This makes our software
rasterizer script fail with
```
ERROR: [Loader Message] Code 0 : libLLVM-15.so.1: cannot open shared object file: No such file or directory
ERROR:             libLLVM-15.so.1: cannot open shared object file: No such file or directory
```
when running vulkaninfo. Surely we can fix this by installing the
necessary dependencies, but for now let's just pin this to the previous
OS version.