Pin python docs build dependencies (#4139)
### What

Fixes the error from
https://github.com/rerun-io/rerun/actions/runs/6744670076/job/18335351486

```
usage: mike [-h] [--version] [--debug] COMMAND ...
mike: error: unrecognized arguments: --rebase --prefix
Error: Process completed with exit code 2.
```

### Checklist
* [x] I have read and agree to [Contributor
Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and
the [Code of
Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested [demo.rerun.io](https://demo.rerun.io/pr/4139) (if
applicable)
* [x] The PR title and labels are set such as to maximize their
usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4139)
- [Docs
preview](https://rerun.io/preview/489e33fda6dd5829b8ca2f0d991dbb291484a5c2/docs)
<!--DOCS-PREVIEW-->
- [Examples
preview](https://rerun.io/preview/489e33fda6dd5829b8ca2f0d991dbb291484a5c2/examples)
<!--EXAMPLES-PREVIEW-->
- [Recent benchmark results](https://ref.rerun.io/dev/bench/)
- [Wasm size tracking](https://ref.rerun.io/dev/sizes/)