Never allow public archetypes without examples (#5111)
At some point we've downgraded the hard error into a warning, probably
when we introduced the experimental blueprint archetypes; and now it's
biting us when we're about to release as we realize we're missing these
examples _and_ the APIs to even write them.

This PR makes it so:
- it is always a hard error to not have examples for public archetypes
- it is always OK to not have examples for stuff in `//testing`
- it is a warning for everything else (incl. experimental stuff, if we
even try to generate doc for it to begin with)

Before:
```
$ RUST_LOG=off just codegen --force
pixi run codegen --force
   Compiling re_types_builder v0.13.0-alpha.3 (/home/cmc/dev/rerun-io/rerun/crates/re_types_builder)
    Finished dev [optimized + debuginfo] target(s) in 2.64s
     Running `target/debug/build_re_types --force`
$ flatc -I /home/cmc/dev/rerun-io/rerun/crates/re_types/definitions -o /tmp/xshell-tmp-dir-0 -b --bfbs-comments --schema /home/cmc/dev/rerun-io/rerun/crates/re_types/definitions/rerun/archetypes.fbs
Warning: //archetypes/series_line.fbs rerun.archetypes.SeriesLine: No examples
Warning: //archetypes/series_point.fbs rerun.archetypes.SeriesPoint: No examples
Warning: //archetypes/series_line.fbs rerun.archetypes.SeriesLine: Missing example
Warning: //archetypes/series_point.fbs rerun.archetypes.SeriesPoint: Missing example
Warning: //blueprint/archetypes/container_blueprint.fbs rerun.blueprint.archetypes.ContainerBlueprint: Missing example
Warning: //blueprint/archetypes/plot_legend.fbs rerun.blueprint.archetypes.PlotLegend: Missing example
Warning: //blueprint/archetypes/scalar_axis.fbs rerun.blueprint.archetypes.ScalarAxis: Missing example
Warning: //blueprint/archetypes/space_view_blueprint.fbs rerun.blueprint.archetypes.SpaceViewBlueprint: Missing example
Warning: //blueprint/archetypes/viewport_blueprint.fbs rerun.blueprint.archetypes.ViewportBlueprint: Missing example
Warning: //testing/archetypes/fuzzy.fbs rerun.testing.archetypes.AffixFuzzer1: Missing example
Warning: //testing/archetypes/fuzzy.fbs rerun.testing.archetypes.AffixFuzzer2: Missing example
Warning: //testing/archetypes/fuzzy.fbs rerun.testing.archetypes.AffixFuzzer3: Missing example
Warning: //testing/archetypes/fuzzy.fbs rerun.testing.archetypes.AffixFuzzer4: Missing example
```

Now:
```
$ RUST_LOG=off just codegen --force
pixi run codegen --force
    Finished dev [optimized + debuginfo] target(s) in 0.14s
     Running `target/debug/build_re_types --force`
$ flatc -I /home/cmc/dev/rerun-io/rerun/crates/re_types/definitions -o /tmp/xshell-tmp-dir-0 -b --bfbs-comments --schema /home/cmc/dev/rerun-io/rerun/crates/re_types/definitions/rerun/archetypes.fbs
Error: //archetypes/series_line.fbs rerun.archetypes.SeriesLine: No examples
Error: //archetypes/series_point.fbs rerun.archetypes.SeriesPoint: No examples
Some errors occurred.
error: Recipe `codegen` failed on line 175 with exit code 1
```

:warning: This will fail CI, because we're missing examples for
`SeriesLine` and `SeriesPoint`! :warning: