Remove backtraces on error when running `rerun` binary (#4746)
### What
* Closes https://github.com/rerun-io/rerun/issues/4738

Starting in [`anyhow
1.0.77`](https://github.com/dtolnay/anyhow/releases/tag/1.0.77), a
backtrace will be printed on error if `RUST_BACKTRACE` is set, and we
set `RUST_BACKTRACE=1` in:


https://github.com/rerun-io/rerun/blob/d204936e4a186b6f264425f7a3d3849f94b7b86f/crates/re_log/src/setup.rs#L32-L35

We do this because we want to print stack traces on panics.

However, for `anyhow::Error` our error messages _should_ be good enough
to not require a stack trace,
so with this PR we now explicitly print out the error instead of relying
in the formatting that happens when returning `anyhow::Result` from
`main`.

### Result
```
❯ cargo run -p rerun-cli --quiet -- .github/workflows/documentation.yaml    
[2024-01-09T10:09:31Z INFO  re_data_source::load_file] Loading ".github/workflows/documentation.yaml"…
Error: ".github/workflows/documentation.yaml" -> No data-loader support for ".github/workflows/documentation.yaml"
```

### Checklist
* [x] I have read and agree to [Contributor
Guide](https://github.com/rerun-io/rerun/blob/main/CONTRIBUTING.md) and
the [Code of
Conduct](https://github.com/rerun-io/rerun/blob/main/CODE_OF_CONDUCT.md)
* [x] I've included a screenshot or gif (if applicable)
* [x] I have tested the web demo (if applicable):
* Using newly built examples:
[app.rerun.io](https://app.rerun.io/pr/4746/index.html)
* Using examples from latest `main` build:
[app.rerun.io](https://app.rerun.io/pr/4746/index.html?manifest_url=https://app.rerun.io/version/main/examples_manifest.json)
* Using full set of examples from `nightly` build:
[app.rerun.io](https://app.rerun.io/pr/4746/index.html?manifest_url=https://app.rerun.io/version/nightly/examples_manifest.json)
* [x] The PR title and labels are set such as to maximize their
usefulness for the next release's CHANGELOG

- [PR Build Summary](https://build.rerun.io/pr/4746)
- [Docs
preview](https://rerun.io/preview/dfadee45bb4767f1e81e2459b8e3f93aabcb5c39/docs)
<!--DOCS-PREVIEW-->
- [Examples
preview](https://rerun.io/preview/dfadee45bb4767f1e81e2459b8e3f93aabcb5c39/examples)
<!--EXAMPLES-PREVIEW-->
- [Recent benchmark results](https://build.rerun.io/graphs/crates.html)
- [Wasm size tracking](https://build.rerun.io/graphs/sizes.html)