[Logging] Update ValueError message on invalid transform type in transform3d_ext.py
The following message is shown in case of using an invalid Type for transformation.
```
RerunWarning: OutOfTreeTransform3DBatch: ValueError(unknown transform 3d value: Scale3D(inner=0.1) (expected `Transform3D`, `TranslationAndMat3x3`, or `TranslationRotationScale`)
```
If you then try to use `TranslationRotationScale` the following shown up
AttributeError: module 'rerun' has no attribute 'TranslationRotationScale'. Did you mean: 'TranslationRotationScale3D'?
```

So we are here updating the ValueError message to show directly the valid TransformType: `TranslationRotationScale3D`