`spawn`: versioned links for missing executable too (#4041)
Fixing an oversight from #4031: if the user doesn't have any executable
at all on their PATH, don't just blindly tell them to download latest,
it might not even be compatible! Use a versioned link in that case too,
where possible.

```sh
$ which rerun
which: no rerun in (...)

$ RUST_LOG=off cargo r -p code_examples --bin point3d_simple

Error: SpawnViewer(Failed to find Rerun Viewer executable in PATH.

    You can install an appropriate version of the Rerun Viewer via binary releases:
    * Using `cargo`: `cargo binstall --force rerun-cli@0.10.0` (see https://github.com/cargo-bins/cargo-binstall)
    * Via direct download from our release assets: https://github.com/rerun-io/rerun/releases/0.10.0/
    * Using `pip`: `pip3 install rerun-sdk==0.10.0` (warning: pip version has slower start times!)

    For more information, refer to our complete install documentation over at:
    https://rerun.io/docs/getting-started/installing-viewer

PATH="...")
```
(This is using my local copy where everything is tagged as if `0.10.0`
was released)