Fix cargo install of CLI (#6076)
```
cargo install --force --path crates/rerun-cli
  Installing rerun-cli v0.16.0-alpha.2 (/home/cmc/dev/rerun-io/rerun/crates/rerun-cli)

error[E0425]: cannot find function `accept` in crate `tungstenite`
   --> crates/re_ws_comms/src/server.rs:217:36
    |
217 |                 match tungstenite::accept(tcp_stream) {
    |                                    ^^^^^^ not found in `tungstenite`
    |
note: found an item that was configured out
   --> /home/cmc/.cargo/registry/src/index.crates.io-6f17d22bba15001f/tungstenite-0.20.1/src/lib.rs:44:14
    |
44  |     server::{accept, accept_hdr, accept_hdr_with_config, accept_with_config},
    |              ^^^^^^
    = note: the item is gated behind the `handshake` feature

For more information about this error, try `rustc --explain E0425`.
warning: `re_ws_comms` (lib) generated 1 warning
error: could not compile `re_ws_comms` (lib) due to 1 previous error; 1 warning emitted
warning: build failed, waiting for other jobs to finish...
error: failed to compile `rerun-cli v0.16.0-alpha.2 (/home/cmc/dev/rerun-io/rerun/crates/rerun-cli)`, intermediate artifacts can be found at `/home/cmc/dev/rerun-io/rerun/target`.
To reuse those artifacts with a future compilation, set the environment variable `CARGO_TARGET_DIR` to that path.
```

Cannot have a server without `accept`, and cannot have `accept` without
`tungstenite/handshake`.

No `Cargo.lock` changes necessary because it was already accounted in
there due to implicit workspace deps union on some other path.